# Generated by Django 4.1.3 on 2023-01-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo_dos', '0003_mensaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
