# Generated by Django 4.1.3 on 2022-12-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0003_vehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(default='rojo', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
